# Generated by Django 5.0.6 on 2024-07-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
